dist: xenial
language: go

sudo: required

go:
  - "1.12.x"
  - "1.13.x"

install:
  - export GO111MODULE=on
  - go mod download

script:
  - go test -v -race -cover -coverprofile=broadcast-ws.txt -covermode=atomic

after_success:
  - curl https://codecov.io/bash -o codecov-bash
  - chmod +x codecov-bash
  - ./codecov-bash -f broadcast-ws.txt