dist: xenial
language: go
sudo: required

go:
  - "1.12.x"

install:
  - export GO111MODULE=on
  - go mod download
  - php -v
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php composer.phar install --no-interaction --prefer-source

script:
  - go test -v -race -cover -coverprofile=broadcast.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -f broadcast.txt

jobs:
  include:
    - stage: Test
      env: "PHP=7.2"
      before_install:
        - sudo add-apt-repository -y ppa:ondrej/php
        - sudo apt-get update
        - sudo apt-get install -y php7.2-cli php7.2-mbstring php7.2-xml php7.2-xdebug
        - sudo cp `which php7.2` `which php`
    - stage: Test
      env: "PHP=7.3"
      before_install:
        - sudo add-apt-repository -y ppa:ondrej/php
        - sudo apt-get update
        - sudo apt-get install -y php7.3-cli php7.3-mbstring php7.3-xml php7.3-xdebug
        - sudo cp `which php7.3` `which php`